OJ_platform/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [

    # 统一登录界面
    path('login/', include('login.urls')),

    # 学生使用界面
    path('student/', include('student_app.urls')),

    # 教师使用界面
    path('teacher/', include('teacher_app.urls')),

    # 课程负责人使用界面
    path('administrator/', include('administrator_app.urls')),

    # 代码查重
    path('codebert/', include('BERT_app.urls')),

    # Django后端管理界面
    path('admin/', admin.site.urls),

    # AI对话-目前使用deepseek
    path('AIchat/', include('AIChat_app.urls')),

    # 代码测试
    path('Testingcode/', include('Testingcode_app.urls')),
]

administrator_app/urls.py
from django.urls import path
from django.contrib.staticfiles.views import serve

from .views import home_administrator, programmingexercise_details_data, home_administrator_exam, exam_details_data
from .views import notice_administrator, create_notice, delete_notice, notification_content
from .views import profile_administrator, profile_administrator_edit, profile_adminadministrator_password
from .views import repository_administrator, programmingexercise_delete, programmingexercise_create
from .views import information_administrator, add_teacher, delete_teacher, reset_password
from .views import problems_administrator, report_administrator, reportdata_delete
from .views import (exam_administrator, admin_examlist_default, admin_examlist,
                    create_adminexam, adminexam_edit, adminexam_delete, adminexamquestion_delete,
                    get_adminexam_cases, adminexamquestion_edit)
from .views import admintest_check_process, get_adminexam_names


app_name = 'administrator_app'

urlpatterns = [
    # 管理员使用界面
    path('home/', home_administrator, name='home_administrator'),
    path('home/programmingexercise_details_data/', programmingexercise_details_data, name='programmingexercise_details_data'),
    path('home/exam/', home_administrator_exam, name='home_administrator_exam'),
    path('home/exam/exam_details_data/', exam_details_data, name='exam_details_data'),
    # 年级考试实况
    path('admintest/', admintest_check_process, name='admintest_check_process'),
    path('admintest/get_adminexam_names/', get_adminexam_names, name='get_adminexam_names'),
    # 有关程序设计题库的操作
    path('repository/', repository_administrator, name='repository_administrator'),
    path('repository/programmingexercise_delete/', programmingexercise_delete, name='programmingexercise_delete'),
    path('repository/programmingexercise_create/', programmingexercise_create, name='programmingexercise_create'),
    # 题库查重管理
    path('problems/', problems_administrator, name='problems_administrator'),
    path('problems/report_administrator/', report_administrator, name='report_administrator'),
    path('problems/reportdata_delete/', reportdata_delete, name='reportdata_delete'),
    # 有关考试的操作
    path('adminexam/', exam_administrator, name='exam_administrator'),
    path('adminexam/adminexam_list/', admin_examlist_default, name='admin_examlist_default'),
    path('adminexam/adminexam_list/<int:exam_id>/', admin_examlist, name='admin_examlist'),
    path('adminexam/adminexam_list/create_exam/<int:exam_id>/', create_adminexam, name='create_adminexam'),
    path('adminexam/delete_exam/', adminexam_delete, name='adminexam_delete'),
    path('adminexam/edit_exam/<int:exam_id>/', adminexam_edit, name='adminexam_edit'),
    path('adminexam/edit_exam/adminexamquestion_delete/', adminexamquestion_delete, name='adminexamquestion_delete'),
    path('adminexam/edit_exam/adminexamquestion_edit/<int:question_id>/', adminexamquestion_edit, name='adminexamquestion_edit'),
    path('adminexam/edit_exam/get_adminexam_cases/<int:question_id>/', get_adminexam_cases, name='get_adminexam_cases'),
    # 有关通知的操作
    path('notice/', notice_administrator, name='notice_administrator'),
    path('notice/create/', create_notice, name='create_notice'),
    path('notice/delete/', delete_notice, name='delete_notice'),
    path('notice/notification_content/', notification_content, name='notification_content'),
    # 教师管理
    path('information/', information_administrator, name='information_administrator'),
    path('information/add_teacher/', add_teacher, name='add_teacher'),
    path('information/delete_teacher/', delete_teacher, name='delete_teacher'),
    path('information/reset_password/', reset_password, name='reset_password'),
    # 个人中心
    path('profile/', profile_administrator, name='profile_administrator'),
    path('profile/edit/', profile_administrator_edit, name='profile_administrator_edit'),
    path('profile/password/', profile_adminadministrator_password, name='profile_administrator_password'),

    path('static/<path:path>', serve),

]

login/urls.py
from django.urls import path
from .views import log_in, log_out
from django.contrib.staticfiles.views import serve

app_name = 'login'

urlpatterns = [
    # 登录界面
    path('', log_in, name='log_in'),
    # 登出
    path('log_out/', log_out, name='log_out'),

    path('static/<path:path>', serve),

]

administrator_app/models.py
from django.db import models

from consumer.models import CustomUser


# Create your models here.
class Administrator(CustomUser):
    name = models.CharField(verbose_name="姓名", max_length=6)
    phone_num = models.CharField(verbose_name="电话号码", max_length=12, null=True)


class AdminNotification(models.Model):
    administrator = models.ForeignKey(Administrator, on_delete=models.CASCADE, related_name='notifications',
                                      verbose_name="课程负责人", null=True, blank=True)
    title = models.CharField(verbose_name="通知标题", max_length=255, null=True, blank=True)
    content = models.TextField(verbose_name="通知内容")
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")


class ProgrammingExercise(models.Model):
    title = models.CharField(verbose_name="题目标题", max_length=255)
    description = models.TextField(verbose_name="题目描述")
    posted_by = models.ForeignKey(Administrator, verbose_name="发布教师", on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    deadline = models.DateTimeField(verbose_name="截止时间")

    def __str__(self):
        return self.title


class AdminExam(models.Model):
    title = models.CharField(verbose_name="考试标题", max_length=255)
    content = models.TextField(verbose_name="考试描述")
    starttime = models.DateTimeField(verbose_name="开始时间")
    deadline = models.DateTimeField(verbose_name="截止时间")
    teacher = models.ForeignKey(Administrator, verbose_name="发布教师", on_delete=models.CASCADE, null=True)
    classes = models.ManyToManyField('teacher_app.Class', verbose_name="参与考试的班级", blank=True)

    def __str__(self):
        return self.title


class AdminExamQuestion(models.Model):
    exam = models.ForeignKey(AdminExam, verbose_name="考试", on_delete=models.CASCADE,
                             related_name='questions', null=True)
    title = models.CharField(max_length=200, verbose_name="题目标题", null=True, blank=True)
    content = models.TextField(verbose_name="题目内容")
    memory_limit = models.IntegerField(verbose_name="内存限制", default=0)
    time_limit = models.IntegerField(verbose_name="时间限制", default=0)
    score = models.IntegerField(verbose_name="分数", default=10)

    def __str__(self):
        return f"{self.exam.title} - {self.content}"


class AdminExamQuestionTestCase(models.Model):
    question = models.ForeignKey(AdminExamQuestion, verbose_name="题目", on_delete=models.CASCADE,
                                 related_name='adminexam_testcases')
    input = models.TextField(verbose_name="测试输入")
    expected_output = models.TextField(verbose_name="预期输出")

    def __str__(self):
        return f"{self.question.title} - {self.question.content}"

administrator_app/views.py
import docx
import pandas as pd
import zipfile
from io import BytesIO
from datetime import datetime, timedelta

from django.contrib.auth.hashers import make_password, check_password
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import DatabaseError
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from BERT_app.views import analyze_programming_report, analyze_programming_code
from administrator_app.models import (Administrator, AdminNotification, ProgrammingExercise,
                                      AdminExam, AdminExamQuestion, AdminExamQuestionTestCase)
from teacher_app.models import Teacher, Class
from student_app.models import Student
from BERT_app.models import ReportStandardScore, ProgrammingCodeFeature, ProgrammingReportFeature
from login.views import login_required
from submissions_app.models import GradeExamSubmission
from Testingcode_app.models import Scores


# 课程负责人主页-程序设计
@login_required
def home_administrator(request):
    try:
        administrator = Administrator.objects.get(pk=request.user.pk)
        user_id = administrator.userid
        # 尝试获取编程练习信息，并按日期倒序排列
        programings = ProgrammingExercise.objects.filter(posted_by=administrator).order_by('-date_posted')
        # 前端模版渲染内容
        context = {
            'active_page': 'home',
            'user_id': user_id,
            'coursework': programings,
        }
        # 正常渲染页面
        return render(request, 'home_administrator.html', context)
    # 捕获会话获取错误
    except KeyError:
        return render(request, 'error.html', {'message': "会话中未找到用户ID"}, status=400)
    # 捕获数据库相关错误
    except DatabaseError as db_err:
        return render(request, 'error.html', {'message': "无法连接到数据库，请稍后重试"}, status=500)
    # 捕获其他未预见的错误
    except Exception as e:
        return render(request, 'error.html', {'message': f"发生未知错误: {e}"}, status=500)

# 课程负责人主页-年级考试
@login_required
def home_administrator_exam(request):
    try:
        administrator = Administrator.objects.get(pk=request.user.pk)
        user_id = administrator.userid
        # 尝试删除标题为"默认标题"的记录
        AdminExam.objects.filter(title="默认标题").delete()
        # 获取所有考试信息，并按开始时间倒序排列
        exams = AdminExam.objects.filter(teacher=administrator).order_by('-starttime')
        # 构建上下文
        context = {
            'active_page': 'home',
            'user_id': user_id,
            'coursework': exams,
        }
        # 正常渲染页面
        return render(request, 'home_administrator_exam.html', context)
        # 捕获会话获取错误
    except KeyError:
        return render(request, 'error.html', {'message': "会话中未找到用户ID"}, status=400)
        # 捕获数据库相关错误
    except DatabaseError as db_err:
        return render(request, 'error.html', {'message': "数据库操作失败，请稍后重试"}, status=500)
        # 捕获其他未预见的错误
    except Exception as e:
        return render(request, 'error.html', {'message': f"发生未知错误: {e}"}, status=500)

# 课程负责人主页-程序设计题详情
@login_required
def programmingexercise_details_data(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    # 尝试获取题目ID
    try:
        if request.method == 'POST':
            question_id = request.POST.get('id')
            # 尝试获取指定的编程练习题
            try:
                question = ProgrammingExercise.objects.get(id=question_id)
                # 获取当前题目所有学生
                teachers = administrator.teachers.all()
                classes = Class.objects.filter(teacher__in=teachers).distinct()
                students = Student.objects.filter(class_assigned__in=classes).distinct()
                total_students = students.count()
                # 获取当前题目所有分数对象，来等效于提交记录
                total_submissions = ReportStandardScore.objects.filter(programming_question=question).count()
                ratio = total_submissions / total_students if total_students else 0
                ratio_data = [{
                    'completion_rate': ratio,
                }]
                context = {
                    'ratio_data': ratio_data,
                }
                return JsonResponse({'data': context}, status=200)
            except ProgrammingExercise.DoesNotExist:
                return JsonResponse({'status': 'error', 'message': '未找到对应的练习题'}, status=404)
        else:
            return JsonResponse({'status': 'error', 'message': '无效的请求方法'}, status=400)
    # 捕获数据库相关错误
    except DatabaseError as db_err:
        return JsonResponse({'status': 'error', 'message': '数据库操作失败，请稍后重试'}, status=500)
    # 捕获其他未预见的错误
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'发生未知错误: {e}'}, status=500)

# 课程负责人主页-年级考试题详情
@login_required
def exam_details_data(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    # 尝试获取题目ID
    try:
        if request.method == 'POST':
            exam_id = request.POST.get('id')
            # 尝试获取指定的考试
            try:
                exam = AdminExam.objects.get(id=exam_id)
                questions = exam.questions.all()
                question_avg_scores = []
                # 遍历所有题目，计算平均分，若学生总数为0，则平均分为0，否则计算平均分
                for question in questions:
                    # 获取当前题目所有分数对象
                    scores = Scores.objects.filter(question_type='adminexam', type_id=exam.id, question_id=question.id)
                    total_score = sum(score.score for score in scores)
                    # 获取当前题目所有学生
                    teachers = administrator.teachers.all()
                    classes = Class.objects.filter(teacher__in=teachers).distinct()
                    students = Student.objects.filter(class_assigned__in=classes).distinct()
                    total_students = students.count()
                    # 计算平均分，若学生总数为0，则平均分为0
                    avg_score = (total_score / total_students) if total_students else 0
                    # 将题目标题和平均分添加到列表中
                    question_avg_scores.append({
                        'question_title': question.title,
                        'average_score': avg_score
                    })
                return JsonResponse({'data': question_avg_scores}, status=200)
            except AdminExam.DoesNotExist:
                return JsonResponse({'status': 'error', 'message': '未找到对应的考试'}, status=404)
        else:
            return JsonResponse({'status': 'error', 'message': '无效的请求方法'}, status=400)
    # 捕获数据库相关错误
    except DatabaseError as db_err:
        return JsonResponse({'status': 'error', 'message': '数据库操作失败，请稍后重试'}, status=500)
    # 捕获其他未预见的错误
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'发生未知错误: {e}'}, status=500)

# 年级考试实况
@login_required
def admintest_check_process(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    user_id = administrator.userid
    # 初始化默认值
    exam_type = None
    exam_id = None
    selected_exam = None
    submissions = []
    # 尝试获取考试类型和考试ID
    if request.method == 'GET':
        exam_type = request.GET.get('exam_type')
        exam_id = request.GET.get('exam_id')
        # 若考试类型和考试ID均存在，则获取对应的考试信息和提交记录
        if exam_type and exam_id:
            selected_exam = AdminExam.objects.filter(id=exam_id).first()
            submissions = GradeExamSubmission.objects.filter(exam=selected_exam).order_by('-submission_time')
        # 渲染页面
        context = {
            'active_page': 'testcheck',
            'user_id': user_id,
            'selected_exam': selected_exam,
            'submissions': submissions,
            'exam_type': exam_type,
            'exam_id': exam_id,
        }
        return render(request, 'admintest_check_process.html', context)

# 年级考试实况-获取考试项目
@login_required
def get_adminexam_names(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    # 尝试获取考试类型
    exam_type = request.GET.get('exam_type')
    # 尝试获取
    try:
        if exam_type == 'adminexam':
            exams = AdminExam.objects.filter(teacher=administrator)
        else:
            exams = []
        # 构建考试名称列表
        exam_names = [{'id': exam.id, 'name': exam.title} for exam in exams]
        return JsonResponse({'exam_names': exam_names})
    except Administrator.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': '未找到管理员信息，请确认用户是否为管理员。'}, status=404)
    except DatabaseError as db_err:
        return JsonResponse({'status': 'error', 'message': '数据库操作失败，请稍后重试。'}, status=500)
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'发生未知错误: {e}'}, status=500)

# GUI程序设计题库
@login_required
def repository_administrator(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    user_id = administrator.userid
    # 获取所有编程练习题，并按日期倒序排列
    programming_exercises = ProgrammingExercise.objects.filter(posted_by=administrator).order_by('-date_posted')
    # 前端模版渲染内容
    context = {
        'active_page': 'guirepository',
        'user_id': user_id,
        'programming_exercises': programming_exercises,
    }
    return render(request, 'repository_administrator.html', context)

# 程序设计题库：添加程序设计题
@login_required
def programmingexercise_create(request):
    administrator = Administrator.objects.get(pk=request.user.pk)
    user_id = administrator.userid
    # 尝试获取POST请求，创建新的编程练习题，若标题、描述、截止时间和发布者均存在，则创建新的编程练习题，并重定向到题库页面，否则渲染创建页面
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('content')
        deadline = request.POST.get('deadline')
        posted_by = administrator.userid
        # 确保标题、描述、截止时间和发布者均存在
        if title and description and deadline and posted_by:
            # 确保 deadline 包含时区信息
            deadline = datetime.fromisoformat(deadline)
            deadline = timezone.make_aware(deadline, timezone.get_current_timezone())
            ProgrammingExercise.objects.create(
                title=title,
                description=description,

administrator_app/templates/adminexam_edit.html
{% extends 'admin_base.html' %}
{% load static %}

{% block title %}考试-题目编辑{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/secondPage.css' %}">    
{% endblock %}

{% block content %}
<!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">考试题列表</p>
                            <div class="table-responsive"
                                 style="max-height: 568px; overflow-y: auto; overflow-x: hidden;">
                                <!-- 添加了 style 属性 -->
                                <div id="recent-purchases-listing_wrapper"
                                     class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                                    <div class="row">
                                        <div class="col-sm-12 col-md-6"></div>
                                        <div class="col-sm-12 col-md-6"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table id="recent-purchases-listing" class="table dataTable no-footer"
                                                   role="grid">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_asc" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-sort="ascending"
                                                        aria-label="Name: activate to sort column descending"
                                                        style="width: 167.95px;">题目
                                                    </th>
                                                    <th class="sorting" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-label="Office: activate to sort column ascending"
                                                        style="width: 155.6px;">内存限制
                                                    </th>
                                                    <th class="sorting" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">时间限制
                                                    </th>
                                                    <th class="sorting" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">题目分值
                                                    </th>
                                                    <th class="sorting" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">测试用例
                                                    </th>
                                                    <th class="sorting" tabindex="0"
                                                        aria-controls="recent-purchases-listing" rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">操作
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for question in exam.questions.all %}
                                                    <tr role="row"
                                                        class="{{ forloop.counter|divisibleby:2|yesno:'even,odd' }}">
                                                        <td class="sorting_1"
                                                            id="question{{ question.id }}"> {{ question.title }}
                                                        </td>
                                                        <td>{{ question.memory_limit }}</td>
                                                        <td>{{ question.time_limit }}</td>
                                                        <td>{{ question.score }}</td>
                                                        <td>
                                                            <button class="button-class view-test-case btn-default"
                                                                    data-question-id="{{ question.id }}">查看
                                                            </button>
                                                        </td>
                                                        <td>
                                                            <button class="button-class edit-test-case btn-default"
                                                                    data-question-id="{{ question.id }}"
                                                                    data-exam-id="{{ exam.id }}">修改
                                                            </button>
                                                            <button class="button-class delete-examquestion btn-default"
                                                                    data-examquestion-id="{{ question.id }}"
                                                                    data-exam-id="{{ exam.id }}">删除
                                                            </button>
                                                        </td>
                                                    </tr>
                                                {% empty %}
                                                    <tr>
                                                        <td colspan="6" style="text-align: center;">没有考试内容</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-5"></div>
                                <div class="col-sm-12 col-md-7">
                                    <button onclick="window.location.href='{% url 'administrator_app:exam_administrator' %}'"
                                            class="btn-default" style="float: right;">返回
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
<!-- 模态框结构 -->
<div class="modal fade" id="testCaseModal" tabindex="-1" role="dialog" aria-labelledby="testCaseModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="testCaseModalLabel">测试用例详情</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Input</th>
                            <th>Output</th>
                        </tr>
                    </thead>
                    <tbody id="testCaseTableBody">
                        <!-- 测试用例数据将被插入到这里 -->
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <!-- 下载按钮 -->
                <button id="downloadTestCases" class="btn btn-primary">下载 Excel</button>
            </div>
        </div>
    </div>
</div>    
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function () {
        $('.delete-examquestion').on('click', function () {
            var questionId = $(this).data('examquestion-id');
            var examId = $(this).data('exam-id');
            if (confirm('确定要删除这个考试题吗？')) {
                $.ajax({
                    url: "{% url 'administrator_app:adminexamquestion_delete' %}",
                    type: 'POST',
                    data: {
                        'exam_id': examId,
                        'question_id': questionId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        window.location.reload();
                    },
                    error: function (response) {
                        alert(response.responseJSON.message);
                    }
                });
            }
        });
    });
</script>    
<script>
    $(document).ready(function () {
        $('.edit-test-case').on('click', function () {
            var questionId = $(this).data('question-id');
            window.location.href = "{% url 'administrator_app:adminexamquestion_edit' question_id=0 %}".replace('0', questionId);
        });
    });
</script>    
<script>
    $(document).ready(function () {
        $('.view-test-case').on('click', function () {
            var questionId = $(this).data('question-id');
            $.ajax({
                url: "{% url 'administrator_app:get_adminexam_cases' question_id=0 %}".replace('0', questionId),
                type: 'GET',
                success: function (response) {
                    if (response.status === "success") {
                        var testCases = response.test_cases;
                        var tableBody = $('#testCaseTableBody');
                        tableBody.empty();  // 清空表格内容

                        // 将测试用例填充到模态框表格中
                        testCases.forEach(function (testCase) {
                            var row = '<tr><td>' + testCase.input + '</td><td>' + testCase.expected_output + '</td></tr>';
                            tableBody.append(row);
                        });

                        // 显示模态框
                        $('#testCaseModal').modal('show');
                        // 设置下载按钮的 URL
                        $('#downloadTestCases').off('click').on('click', function () {
                            window.location.href = "{% url 'administrator_app:get_adminexam_cases' question_id=0 %}?download=true".replace('0', questionId);
                        });
                    } else {
                        alert('无法获取测试用例，请重试。');
                    }
                },
                error: function () {
                    alert('请求失败，请重试。');
                }
            });
        });
    });
</script>    
{% endblock %}