OJ_platform/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [

    # 统一登录界面
    path('login/', include('login.urls')),

    # 学生使用界面
    path('student/', include('student_app.urls')),

    # 教师使用界面
    path('teacher/', include('teacher_app.urls')),

    # 课程负责人使用界面
    path('administrator/', include('administrator_app.urls')),

    # 代码查重
    path('codebert/', include('BERT_app.urls')),

    # Django后端管理界面
    path('admin/', admin.site.urls),

    # AI对话-目前使用deepseek
    path('AIchat/', include('AIChat_app.urls')),

    # 代码测试
    path('Testingcode/', include('Testingcode_app.urls')),
]

login/urls.py
from django.urls import path
from .views import log_in, log_out
from django.contrib.staticfiles.views import serve

app_name = 'login'

urlpatterns = [
    # 登录界面
    path('', log_in, name='log_in'),
    # 登出
    path('log_out/', log_out, name='log_out'),

    path('static/<path:path>', serve),

]

student_app/urls.py
# student_app/urls.py
from django.urls import path
from django.contrib.staticfiles.views import serve

from .views import home_student, practice_student, exam_student, profile_student, report_student
from .views import teacherexam_list, practice_list, notification_content, adminexam_list
from .views import analyse_exercise, analyse_exam, analyse_data
from .views import coding_exercise, coding_exam, coding_adminexam
from .views import profile_student_edit, profile_student_password
# 开发环境配置
from django.conf import settings
from django.conf.urls.static import static


app_name = 'student_app'


urlpatterns = [
    # 学生主页
    path('home/', home_student, name='home_student'),
    path('home/report_student/<int:programmingexercise_id>/', report_student, name='report_student'),
    # 练习相关
    path('practice/', practice_student, name='practice_student'),
    path('practice/practice_list/<int:exercise_id>/', practice_list, name='practice_list'),
    path('coding_exercise/<int:exercisequestion_id>/', coding_exercise, name='coding_exercise'),
    # 考试相关
    path('exam/', exam_student, name='exam_student'),
    path('exam/exam_list/<int:exam_id>/', teacherexam_list, name='teacherexam_list'),
    path('exam/adminexam_list/<int:exam_id>/', adminexam_list, name='adminexam_list'),
    path('coding_exam/<int:examquestion_id>/', coding_exam, name='coding_exam'),
    path('coding_adminexam/<int:examquestion_id>/', coding_adminexam, name='coding_adminexam'),
    # 学情分析相关
    path('analyse_exercise/', analyse_exercise, name='analyse_exercise'),
    path('analyse_exam/', analyse_exam, name='analyse_exam'),
    path('analyse_data/', analyse_data, name='analyse_data'),
    # 学生个人中心
    path('profile/', profile_student, name='profile_student'),
    path('profile/edit/', profile_student_edit, name='profile_student_edit'),
    path('profile/password/', profile_student_password, name='profile_student_password'),
    # 通知相关
    path('notification_content/', notification_content, name='notification_content'),

    path('static/<path:path>', serve),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_app/models.py
from django.db import models

from consumer.models import CustomUser
from teacher_app.models import Class, ExerciseQuestion, ExamQuestion, Exercise, Exam
from administrator_app.models import AdminExam, AdminExamQuestion


# Create your models here.
class Student(CustomUser):
    name = models.CharField(verbose_name="姓名", max_length=6)
    class_assigned = models.ForeignKey(Class, on_delete=models.CASCADE, verbose_name="班级",
                                       null=True, blank=True, related_name='students')

student_app/views.py
import os
import docx
import tempfile
from io import BytesIO

from django.utils import timezone
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password, check_password

from administrator_app.models import ProgrammingExercise, AdminExam, AdminExamQuestion
from student_app.models import Student
from teacher_app.models import Notification, Exercise, Exam, ExerciseQuestion, ExamQuestion, ReportScore
from BERT_app.views import (analyze_programming_report,
                            score_report, analyze_programming_code)
from login.views import login_required
from Testingcode_app.models import (Scores)


# 学生主页
@login_required
def home_student(request):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    # 获取GUI编程题目
    teacher = student.class_assigned.teacher
    programing_exercises = ProgrammingExercise.objects.filter(posted_by=teacher.course_coordinator).order_by('-date_posted')
    # 前端模版渲染内容
    context = {
        'active_page': 'home',
        'user_id': user_id,
        'notifications': notifications,
        'programing_exercises': programing_exercises,
    }
    return render(request, 'home_student.html', context)

# 学生主页：提交报告
@login_required
def report_student(request, programmingexercise_id):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取课程负责人发布的GUI编程题目
    programming_exercise = get_object_or_404(ProgrammingExercise, id=programmingexercise_id)
    # GET请求时发送渲染内容，并获取学生所在班级的通知
    if request.method == 'GET':
        notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
        # 前端模版渲染内容
        context = {
            'active_page': 'home',
            'user_id': user_id,
            'notifications': notifications,
            'programming_exercise': programming_exercise,
        }
        return render(request, 'report_student.html', context)
    # 检查截止时间
    if timezone.now() > programming_exercise.deadline:
        return JsonResponse({'status': 'error', 'message': '截止时间已到，不能提交报告'}, status=400)
    # POST请求时处理提交的报告
    if request.method == 'POST':
        reportstandards = ReportScore.objects.filter(teacher=student.class_assigned.teacher)
        if reportstandards:
            word_file = request.FILES.get('wordFile')
            if word_file:
                try:
                    # 读取文件内容并使用BytesIO创建一个类似文件的对象
                    word_file_bytes = BytesIO(word_file.read())
                    # 使用BytesIO对象创建docx文档对象
                    document = docx.Document(word_file_bytes)
                    full_text = []
                    for paragraph in document.paragraphs:
                        full_text.append(paragraph.text)
                    # 获得纯文本代码，去除了图片
                    report = '\n'.join(full_text)
                    # 分析报告特征
                    analyze_programming_report(student, report, programmingexercise_id)
                    # 报告规范性评分
                    score_report(student, document, programmingexercise_id)
                except Exception as e:
                    return JsonResponse({'status': 'error', 'message': f'处理Word文件时出错: {str(e)}'}, status=400)
            # 读取TXT文件内容
            code_file = request.FILES.get('txtFile')
            if code_file:
                try:
                    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".txt")
                    temp_file.write(code_file.read())
                    temp_file.close()
                    # 分析代码特征
                    code = open(temp_file.name, encoding='utf-8').read()
                    analyze_programming_code(student, code, programmingexercise_id)
                    # 删除临时文件
                    os.unlink(temp_file.name)
                except Exception as e:
                    return JsonResponse({'status': 'error', 'message': f'处理TXT文件时出错: {str(e)}'}, status=400)
            return JsonResponse({'status': 'success', 'message': '提交成功'}, status=200)
        else:
            return JsonResponse({'status': 'error', 'message': '教师未设置报告规范性评分标准'}, status=400)

# 我的练习
@login_required
def practice_student(request):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知、班级的练习题目
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    exercises = Exercise.objects.filter(classes=student.class_assigned).order_by('-published_at')
    # 前端模版渲染内容
    context = {
        'active_page': 'practice',
        'user_id': user_id,
        'exercises': exercises,
        'notifications': notifications,
    }
    return render(request, 'practice_student.html', context)

# 我的练习：练习详情
@login_required
def practice_list(request, exercise_id):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    if request.method == 'GET':
        exercise = Exercise.objects.get(id=exercise_id)
        # 前端模版渲染内容
        context = {
            'active_page': 'practice',
            'user_id': user_id,
            'exercise': exercise,
            'notifications': notifications,
        }
        return render(request, 'practice_list.html', context)

# 我的考试
@login_required
def exam_student(request):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知、教师发布的班级考试th_exams、课程负责人发布的年级考试admin_exams
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    th_exams = Exam.objects.filter(classes=student.class_assigned).order_by('-starttime')
    admin_exams = AdminExam.objects.filter(classes=student.class_assigned).order_by('-starttime')
    # 前端模版渲染内容
    context = {
        'active_page': 'exam',
        'user_id': user_id,
        'th_exams': th_exams,
        'admin_exams': admin_exams,
        'notifications': notifications,
    }
    return render(request, 'exam_student.html', context)

# 我的考试：教师考试详情
@login_required
def teacherexam_list(request, exam_id):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    if request.method == 'GET':
        exam = Exam.objects.get(id=exam_id)
        # 前端模版渲染内容
        context = {
            'active_page': 'exam',
            'user_id': user_id,
            'exam': exam,
            'notifications': notifications,
        }
        return render(request, 'teacherexam_list.html', context)

# 我的考试：管理员考试详情
@login_required
def adminexam_list(request, exam_id):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    # 获取学生所在班级的通知
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    if request.method == 'GET':
        exam = AdminExam.objects.get(id=exam_id)
        # 前端模版渲染内容
        context = {
            'active_page': 'exam',
            'user_id': user_id,
            'exam': exam,
            'notifications': notifications,
        }
        return render(request, 'adminexam_list.html', context)

# 学情分析-班级练习
@login_required
def analyse_exercise(request):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    exercises = Exercise.objects.filter(classes=student.class_assigned).order_by('-published_at')
    # 前端模版渲染内容
    context = {
        'active_page': 'analyse',
        'user_id': user_id,
        'notifications': notifications,
        'coursework': exercises,
    }
    return render(request, 'analyse_exercise.html', context)

# 学情分析-班级考试
@login_required
def analyse_exam(request):
    student = Student.objects.get(pk=request.user.pk)
    user_id = student.userid
    notifications = Notification.objects.filter(recipients=student.class_assigned).order_by('-date_posted')
    exams = Exam.objects.filter(classes=student.class_assigned).order_by('-starttime')
    # 前端模版渲染内容
    context = {
        'active_page': 'analyse',
        'user_id': user_id,
        'notifications': notifications,
        'coursework': exams,
    }
    return render(request, 'analyse_exam.html', context)

# 学情分析-获取数据
@login_required
def analyse_data(request):
    student = Student.objects.get(pk=request.user.pk)
    class_assigned = student.class_assigned
    if request.method == 'POST':
        data_type = request.POST.get('type')
        item_id = request.POST.get('id')
        # 获取练习的平均得分和具体的题目得分
        if data_type == 'exercise':
            # 计算每个练习的平均得分
            exercises = Exercise.objects.filter(classes=class_assigned)
            exercise_avg_scores = []
            for ex in exercises:
                question_count = ex.questions.count()  # 使用 related_name 获取相关的练习题数量
                ex_questions = ExerciseQuestion.objects.filter(exercise=ex)
                # 计算这次练习的所有题目的总得分
                total_score = Scores.objects.filter(
                    student=student,
                    question_type='exercise',
                    type_id=ex.id,
                    question_id__in=ex_questions.values_list('id', flat=True)
                ).aggregate(total_score=Sum('score'))['total_score']
                # 如果没有找到得分，则为该练习设置得分为0
                if total_score is None:
                    total_score = 0
                avg_score = total_score / question_count  # 计算平均得分 (总得分 / 题目数量)
                # 将平均得分添加到列表中
                exercise_avg_scores.append({

student_app/templates/adminexam_list.html
{% extends 'student_base.html' %}
{% load static %}

{% block title %}年级考试-考试详情{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/secondPage.css' %}">
{% endblock %}

{% block content %}
<!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row d-flex" id="proBanner">
                    <div class="col-md-12 grid-margin">
                        <div class="card bg-gradient-primary border-0">
                            <div class="card-body py-3 px-4 d-flex align-items-center justify-content-between flex-wrap">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">考试题目</p>
                            <div class="table-responsive"
                                 style="max-height: 450px; overflow-y: auto; overflow-x: hidden;">
                                <div id="exam-listing_wrapper"
                                     class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table id="exam-listing" class="table dataTable no-footer" role="grid">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_asc" tabindex="0" aria-controls="exam-listing"
                                                        rowspan="1" colspan="1" aria-sort="ascending"
                                                        aria-label="Name: activate to sort column descending"
                                                        style="width: 167.95px;">题目
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="exam-listing"
                                                        rowspan="1" colspan="1"
                                                        aria-label="Office: activate to sort column ascending"
                                                        style="width: 155.6px;">开始时间
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="exam-listing"
                                                        rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">截止时间
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="exam-listing"
                                                        rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">发布教师
                                                    </th>
                                                    <th class="sorting" tabindex="0" aria-controls="exam-listing"
                                                        rowspan="1" colspan="1"
                                                        aria-label="Price: activate to sort column ascending"
                                                        style="width: 72.575px;">操作
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for question in exam.questions.all %}
                                                    <tr role="row"
                                                        class="{{ forloop.counter|divisibleby:2|yesno:'even,odd' }}">
                                                        <td class="sorting_1"
                                                            id="question{{ question.id }}"> {{ question.title }}
                                                        </td>
                                                        <td>{{ exam.starttime }}</td>
                                                        <td>{{ exam.deadline }}</td>
                                                        <td>{{ exam.teacher.name }}</td>
                                                        <td>
                                                            <button class="button-class doing-question btn-default"
                                                                    data-question-id="{{ question.id }}">开始作答
                                                            </button>
                                                        </td>
                                                    </tr>
                                                {% empty %}
                                                    <tr>
                                                        <td colspan="4" style="text-align: center;">没有考试题目</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-5"></div>
                                <div class="col-sm-12 col-md-7">
                                    <button onclick="window.location.href='{% url 'student_app:exam_student' %}'"
                                            class="btn-default" style="float: right;">返回
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function () {
        $('.doing-question').on('click', function () {
            var questionId = $(this).data('question-id');
            var url = "{% url 'student_app:coding_adminexam' '123' %}".replace('123', questionId);

            $.ajax({
                url: url,
                type: "GET",
                success: function (response) {
                    window.location.href = url;
                },
                error: function (response) {
                    alert(response.responseJSON.message);
                }
            });
        });
    });
</script>
{% endblock %}

student_app/templates/analyse_exam.html
{% extends 'student_base.html' %}

{% block title %}学情分析{% endblock %}

{% block extra_css %}
<style>
        table tbody tr:hover {
            background-color: #f2f2f2;
        }
</style>
{% endblock %}

{% block content %}
<!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row d-flex" id="proBanner">
                    <div class="col-md-12 grid-margin">
                        <div class="card bg-gradient-primary border-0">
                            <div class="card-body py-3 px-4 d-flex align-items-center justify-content-between flex-wrap">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body dashboard-tabs p-0">
                                <div class="tab-content py-0 px-0">
                                    <!--得分情况-->
                                    <div class="row">
                                        <div class="col-md-7 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <p class="card-title">题目得分</p>
                                                    <div id="cash-deposits-chart-legend"
                                                         class="d-flex justify-content-center pt-3"></div>
                                                    <!-- Replace the content of this div -->
                                                    <div id="barChart" style="width: 600px;height:400px;"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--练习考试切换-->
                                        <div class="col-md-5 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <!-- 添加切换按钮 -->
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <button type="button" class="btn btn-secondary exercise-button"
                                                                data-type="exercise">练习
                                                        </button>
                                                        <button type="button" class="btn btn-secondary"
                                                                data-type="exam">考试
                                                        </button>
                                                    </div>
                                                    <div class="table-responsive"
                                                         style="max-height: 300px; overflow-y: auto; overflow-x: hidden;">
                                                        <div class="row">
                                                            <table class="table">
                                                                <thead>
                                                                <tr>
                                                                    <th scope="col">名称</th>
                                                                    <th scope="col">截止时间</th>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                {% for question in coursework %}
                                                                    <tr data-id="{{ question.id }}">
                                                                        <td>{{ question.title }}</td>
                                                                        <td>{{ question.deadline }}</td>
                                                                    </tr>
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">我的成绩</p>
                            <div class="card-container">
                                <div id="lineChart" style="width: 1000px;height:400px;"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block extra_js %}
<script>
    // 基于准备好的dom，初始化echarts实例
    var lineChart = echarts.init(document.getElementById('lineChart'));
    // 指定图表的配置项和数据
    var lineOption = {
        title: {
            text: '综合得分趋势',
            x: 'center'
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross',
                label: {
                    backgroundColor: '#6a7985'
                }
            }
        },
        legend: {
            orient: 'horizontal',
            left: 'left',
            data: ['得分']
        },
        toolbox: {
            feature: {
                saveAsImage: {}
            }
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis: {
            type: 'category',
            boundaryGap: false,
            data: ['考试一', '考试二', '考试三', '考试四', '考试五', '考试六']
        },
        yAxis: {
            type: 'value'
        },
        series: [
            {
                name: '得分',
                type: 'line',
                data: [2.6, 7.0, 5.4, 10, 6.1, 3.4]
            }
        ]
    };
    lineChart.setOption(lineOption);
</script>
<script>
    // 基于准备好的dom，初始化echarts实例
    var barChart = echarts.init(document.getElementById('barChart'));
    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '',
            x: 'center'
        },
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'shadow'
            }
        },
        legend: {
            data: ['得分']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        xAxis: {
            type: 'category',
            data: ['题目1', '题目2', '题目3', '题目4', '题目5', '题目6', '题目7'] // 示例题目名称
        },
        yAxis: {
            type: 'value'
        },
        series: [
            {
                name: '得分',
                type: 'bar',
                data: [10, 3, 6, 3, 1, 4, 3] // 示例得分数据
            }
        ]
    };
    barChart.setOption(option);
</script>
<script>
    $(function () {
        $('.btn-group .btn-secondary[data-type="exam"]').addClass('active')

        $('.btn-group .btn-secondary.exercise-button').click(function () {
            window.location.href = "{% url 'student_app:analyse_exercise' %}"
        });

        $('table tbody').on('click', 'tr', function () {
            var id = $(this).data('id');
            var type = $('.btn-group .btn-secondary.active').data('type');
            $.ajax({
                url: "{% url 'student_app:analyse_data' %}",
                type: 'POST',
                data: {
                    'id': id,
                    'type': type,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (response) {
                    var data = response.data;
                    updateLineChart(data.avg_scores);
                    updateBarChart(data.question_scores);
                },
                error: function (response) {
                    alert(response.responseJSON.message);
                }
            });
        });
    })

    // 更新折线图的函数
    function updateLineChart(data) {
        var myChart = echarts.init(document.getElementById('lineChart'));
        var option = {
            title: {
                text: '综合得分趋势'
            },
            tooltip: {
                trigger: 'axis'
            },
            legend: {
                data: ['得分']
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                type: 'category',
                data: data.map(function (item) {
                    return item.exam_title;
                })
            },
            yAxis: {
                type: 'value'
            },
            series: [{
                name: '得分',
                type: 'line',
                data: data.map(function (item) {
                    return item.avg_score;
                })
            }]
        };
        myChart.setOption(option);
    }

    // 更新柱状图的函数
    function updateBarChart(data) {
        var barChart = echarts.init(document.getElementById('barChart'));
        var option = {
            tooltip: {
                trigger: 'axis'
            },
            legend: {
                data: ['题目']
            },
            xAxis: {
                type: 'category',
                data: data.map(function (item) {
                    return item.question_title;
                })
            },
            yAxis: {
                type: 'value',
            },
            series: [{
                name: '题目',
                type: 'bar',
                data: data.map(function (item) {
                    return item.scores;
                }),
                barWidth: '55'
            }]
        };
        barChart.setOption(option);
    }
</script>
<script>
    $(document).ready(function () {
        $("table tbody tr").click(function () {
            $("table tbody tr").css("background-color", ""); // 添加这行，恢复所有行原本的背景颜色
            $(this).css("background-color", "#f2f2f2"); // 让点击的那一行变为灰色
        });
    });
</script>
{% endblock %}