OJ_platform/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [

    # 统一登录界面
    path('login/', include('login.urls')),

    # 学生使用界面
    path('student/', include('student_app.urls')),

    # 教师使用界面
    path('teacher/', include('teacher_app.urls')),

    # 课程负责人使用界面
    path('administrator/', include('administrator_app.urls')),

    # 代码查重
    path('codebert/', include('BERT_app.urls')),

    # Django后端管理界面
    path('admin/', admin.site.urls),

    # AI对话-目前使用deepseek
    path('AIchat/', include('AIChat_app.urls')),

    # 代码测试
    path('Testingcode/', include('Testingcode_app.urls')),
]

login/urls.py
from django.urls import path
from .views import log_in, log_out
from django.contrib.staticfiles.views import serve

app_name = 'login'

urlpatterns = [
    # 登录界面
    path('', log_in, name='log_in'),
    # 登出
    path('log_out/', log_out, name='log_out'),

    path('static/<path:path>', serve),

]

teacher_app/urls.py
from django.urls import path
from django.contrib.staticfiles.views import serve

from .views import home_teacher, repeat_report, repeat_report_details, repeat_code_details
from .views import profile_teacher, profile_teacher_edit, profile_teacher_password
from .views import class_teacher, create_class, delete_class, class_details, delete_student, reset_password
from .views import (repository_teacher, exercise_list_default, exercise_list,
                    create_exercise, exercise_delete, exercise_edit, exercisequestion_delete,
                    get_exercise_cases, exercisequestion_edit)
from .views import (exam_list_default, exam_list,
                    create_exam, exam_delete, exam_edit, examquestion_delete, examquestion_edit, get_exam_cases)
from .views import notice_teacher, create_notice, delete_notice, notification_content
from .views import (coursework_exercise, coursework_exam, coursework_adminexam, coursework_data,
                    coursework_exercise_details, coursework_exam_details, coursework_adminexam_details,
                    coursework_details_data)
from .views import standard_report, scores_details
from .views import test_check_process, get_exam_names


app_name = 'teacher_app'


urlpatterns = [
    # 教师使用界面
    path('home/', home_teacher, name='home_teacher'),
    path('home/standard_report/', standard_report, name='standard_report'),
    path('home/repeat_report/<int:programmingexercise_id>/', repeat_report, name='repeat_report'),
    path('home/repeat_report/report_details/<int:programmingexercise_id>/', repeat_report_details, name='repeat_report_details'),
    path('home/repeat_report/code_details/<int:programmingexercise_id>/', repeat_code_details, name='repeat_code_details'),
    path('home/repeat_report/scores_details/<int:programmingexercise_id>/', scores_details, name='scores_details'),
    # 有关考试实况的操作
    path('test/', test_check_process, name='test_check_process'),
    path('test/get_exam_names/', get_exam_names, name='get_exam_names'),
    # 有关的coursework操作
    path('coursework/exercise/', coursework_exercise, name='coursework_exercise'),
    path('coursework/exam/', coursework_exam, name='coursework_exam'),
    path('coursework/adminexam/', coursework_adminexam, name='coursework_adminexam'),
    path('coursework/data/', coursework_data, name='coursework_data'),
    path('coursework/exercise/details/<int:class_id>/', coursework_exercise_details, name='coursework_exercise_details'),
    path('coursework/exam/details/<int:class_id>/', coursework_exam_details, name='coursework_exam_details'),
    path('coursework/adminexam/details/<int:class_id>/', coursework_adminexam_details, name='coursework_adminexam_details'),
    path('coursework/details/data/', coursework_details_data, name='coursework_details_data'),
    # 有关通知的操作
    path('notice/', notice_teacher, name='notice_teacher'),
    path('notice/create/', create_notice, name='create_notice'),
    path('notice/delete/', delete_notice, name='delete_notice'),
    path('notice/notification_content/', notification_content, name='notification_content'),
    # 有关题库的操作：练习
    path('repository/', repository_teacher, name='repository_teacher'),
    path('repository/exercise_list/', exercise_list_default, name='exercise_list_default'),
    path('repository/exercise_list/<int:exercise_id>/', exercise_list, name='exercise_list'),
    path('repository/exercise_list/create_exercise/<int:exercise_id>/', create_exercise, name='create_exercise'),
    path('repository/delete_exercise/', exercise_delete, name='exercise_delete'),
    path('repository/edit_exercise/<int:exercise_id>/', exercise_edit, name='exercise_edit'),
    path('repository/edit_exercise/exercisequestion_delete/', exercisequestion_delete, name='exercisequestion_delete'),
    path('repository/edit_exercise/exercisequestion_edit/<int:question_id>/', exercisequestion_edit, name='exercisequestion_edit'),
    path('repository/edit_exercise/get_exercise_cases/<int:question_id>/', get_exercise_cases, name='get_exercise_cases'),
    # 有关题库的操作：考试
    path('repository/exam_list/', exam_list_default, name='exam_list_default'),
    path('repository/exam_list/<int:exam_id>/', exam_list, name='exam_list'),
    path('repository/exam_list/create_exam/<int:exam_id>/', create_exam, name='create_exam'),
    path('repository/delete_exam/', exam_delete, name='exam_delete'),
    path('repository/edit_exam/<int:exam_id>/', exam_edit, name='exam_edit'),
    path('repository/edit_exam/examquestion_delete/', examquestion_delete, name='examquestion_delete'),
    path('repository/edit_exam/examquestion_edit/<int:question_id>/', examquestion_edit, name='examquestion_edit'),
    path('repository/edit_exam/get_exam_cases/<int:question_id>/', get_exam_cases, name='get_exam_cases'),
    # 有关班级的操作
    path('class/', class_teacher, name='class_teacher'),
    path('class/create/', create_class, name='create_class'),
    path('class/delete/', delete_class, name='delete_class'),
    path('class/class_details/<int:class_id>/', class_details, name='class_details'),
    path('class/class_details/delete_student/', delete_student, name='delete_student'),
    path('class/class_details/reset_password/', reset_password, name='reset_password'),
    # 个人中心
    path('profile/', profile_teacher, name='profile_teacher'),
    path('profile/edit/', profile_teacher_edit, name='profile_teacher_edit'),
    path('profile/password/', profile_teacher_password, name='profile_teacher_password'),

    path('static/<path:path>', serve),

]

teacher_app/views.py
import pandas as pd
from datetime import datetime, timedelta
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse, HttpResponseNotFound, HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone

from BERT_app.models import ProgrammingCodeFeature, ProgrammingReportFeature, ReportStandardScore
from BERT_app.views import compute_cosine_similarity
from administrator_app.models import AdminNotification, ProgrammingExercise, AdminExam, AdminExamQuestion
from login.views import login_required
from teacher_app.models import (Teacher, Class, Notification,
                                Exercise, ExerciseQuestion, Exam, ExamQuestion, ReportScore,
                                ExerciseQuestionTestCase, ExamQuestionTestCase)
from student_app.models import Student
from submissions_app.models import ClassExamSubmission, GradeExamSubmission
from Testingcode_app.models import (ExerciseCompletion, ExamCompletion, Scores,
                                    ExerciseQuestionCompletion, ExamQuestionCompletion,
                                    AdminExamCompletion, AdminExamQuestionCompletion)


# 教师主页
@login_required
def home_teacher(request):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取教师与之关联的课程负责人发布的通知和GUI编程题目
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    programing_exercises = ProgrammingExercise.objects.filter(posted_by=teacher.course_coordinator).order_by('-date_posted')
    # 前端模板渲染内容
    context = {
        'active_page': 'home',
        'user_id': user_id,
        'adminnotifications': adminnotifications,
        'programing_exercises': programing_exercises
    }
    return render(request, 'home_teacher.html', context)

# 教师主页-查看报告
@login_required
def repeat_report(request, programmingexercise_id):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取课程负责人发布的通知、教师所教授的班级
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    classes = Class.objects.filter(teacher=teacher)
    # 前端模板渲染内容
    context = {
        'active_page': 'home',
        'user_id': user_id,
        'adminnotifications': adminnotifications,
        'classes': classes,
        'programmingexercise_id': programmingexercise_id
    }
    return render(request, 'similarity_report.html', context)

# 教师主页-查看报告-获取文本数据
@login_required
def repeat_report_details(request, programmingexercise_id):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取GET请求中的class_id参数，获取与该班级关联的所有学生；获取特定的编程题目
    class_id = request.GET.get('class_id')
    students = Student.objects.filter(class_assigned=class_id)
    programmingexercise = ProgrammingExercise.objects.get(id=programmingexercise_id)
    student_similarities = []
    # 遍历所有学生，计算余弦相似度
    for student in students:
        # 尝试获取当前学生对于特定练习题的编程特征，否则为None
        try:
            student_feature = ProgrammingReportFeature.objects.get(student=student, programming_question=programmingexercise)
        except ProgrammingReportFeature.DoesNotExist:
            student_feature = None
        # 如果学生特征存在，计算余弦相似度，找到最相似的学生，存储最大相似度值和学生对象，更新或创建当前学生的余弦相似度记录，否则将相似度设置为None
        if student_feature:
            max_similarity = 0
            sim_student = None
            # 排除当前学生的其他特征
            other_features = ProgrammingReportFeature.objects.filter(programming_question=programmingexercise).exclude(student=student)
            # 遍历其他学生的特征，计算余弦相似度
            for other_feature_record in other_features:
                similarity = compute_cosine_similarity(student_feature.feature, other_feature_record.feature)
                if similarity > max_similarity:
                    max_similarity = similarity
                    sim_student = other_feature_record.student
            # 在列表中为当前学生存储最大相似度值和学生对象
            student_similarities.append((student, max_similarity, sim_student))
            # 更新或创建当前学生的余弦相似度记录
            ProgrammingReportFeature.objects.update_or_create(
                student=student,
                programming_question=programmingexercise,
                defaults={'cosine_similarity': max_similarity, 'similar_student': sim_student}
            )
        else:
            # 如果没有学生特征，我们将相似度设置为None
            student_similarities.append((student, None, None))
    # 获取课程负责人发布的通知、教师所教授的班级
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    classes = Class.objects.filter(teacher=teacher)
    # 前端模板渲染内容
    context = {
        'active_page': 'home',
        'user_id': user_id,
        'adminnotifications': adminnotifications,
        'classes': classes,
        'programmingexercise_id': programmingexercise_id,
        'students': students,
        'student_similarities': student_similarities,
    }
    return render(request, 'similarity_report_details.html', context)

# 教师主页-查看报告-获取代码数据
@login_required
def repeat_code_details(request, programmingexercise_id):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取GET请求中的class_id参数，获取与该班级关联的所有学生；获取特定的编程题目
    class_id = request.GET.get('class_id')
    students = Student.objects.filter(class_assigned=class_id)
    programmingexercise = ProgrammingExercise.objects.get(id=programmingexercise_id)
    student_similarities = []
    # 遍历所有学生，计算余弦相似度
    for student in students:
        # 尝试获取当前学生对于特定练习题的编程特征，否则为None
        try:
            student_feature = ProgrammingCodeFeature.objects.get(student=student, programming_question=programmingexercise)
        except ProgrammingCodeFeature.DoesNotExist:
            student_feature = None
        # 如果学生特征存在，计算余弦相似度，找到最相似的学生，存储最大相似度值和学生对象，更新或创建当前学生的余弦相似度记录，否则将相似度设置为None
        if student_feature:
            max_similarity = 0
            sim_student = None
            other_features = ProgrammingCodeFeature.objects.filter(programming_question=programmingexercise).exclude(student=student)
            # 遍历其他学生的特征，计算余弦相似度
            for other_feature_record in other_features:
                similarity = compute_cosine_similarity(student_feature.feature, other_feature_record.feature)
                if similarity > max_similarity:
                    max_similarity = similarity
                    sim_student = other_feature_record.student
            # 在列表中为当前学生存储最大相似度值和学生对象
            student_similarities.append((student, max_similarity, sim_student))
            # 更新或创建当前学生的余弦相似度记录
            ProgrammingCodeFeature.objects.update_or_create(
                student=student,
                programming_question=programmingexercise,
                defaults={'cosine_similarity': max_similarity, 'similar_student': sim_student}
            )
        else:
            # 如果没有学生特征，将相似度设置为None
            student_similarities.append((student, None, None))
    # 获取课程负责人发布的通知、教师所教授的班级
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    classes = Class.objects.filter(teacher=teacher)
    # 前端模板渲染内容
    context = {
        'active_page': 'home',
        'user_id': user_id,
        'adminnotifications': adminnotifications,
        'classes': classes,
        'programmingexercise_id': programmingexercise_id,
        'students': students,
        'student_similarities': student_similarities,
    }
    return render(request, 'similarity_code_details.html', context)

# 教师主页-规范性评分
@login_required
def standard_report(request):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取课程负责人发布的通知
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    # 尝试获取教师的标准报告评分，否则为None
    try:
        stand_score = ReportScore.objects.get(teacher=teacher)
    except ObjectDoesNotExist:
        stand_score = None
    # 如果标准报告评分已经存在，前端模板渲染内容添加标准报告评分字段
    if stand_score:
        context = {
            'active_page': 'home',
            'user_id': user_id,
            'adminnotifications': adminnotifications,
            'stand_score': stand_score,
        }
    else:
        context = {
            'active_page': 'home',
            'user_id': user_id,
            'adminnotifications': adminnotifications,
        }
    if request.method == 'POST':
        totalscore = request.POST.get('totalscore')
        contents = request.POST.get('contents')
        firstrow = request.POST.get('firstrow')
        fontsize = request.POST.get('fontsize')
        image = request.POST.get('image')
        pagenum = request.POST.get('pagenum')
        # 更新或创建教师的标准报告评分
        ReportScore.objects.update_or_create(
            teacher=teacher,
            defaults={
                'totalscore': totalscore,
                'contents': contents,
                'firstrow': firstrow,
                'fontsize': fontsize,
                'image': image,
                'pagenum': pagenum,
            }
        )
        return redirect('teacher_app:standard_report')
    return render(request, 'standard_report.html', context)

# 教师主页-查看报告-得分详情
@login_required
def scores_details(request, programmingexercise_id):
    teacher = Teacher.objects.get(pk=request.user.pk)
    user_id = teacher.userid
    # 获取特定编程题目，班级所有学生的代码规范性得分
    classes = Class.objects.filter(teacher=teacher)
    adminnotifications = AdminNotification.objects.filter(administrator=teacher.course_coordinator).order_by('-date_posted')
    # 获取GET请求中的class_id参数，获取与该班级关联的所有学生；获取特定的编程题目
    class_id = request.GET.get('class_id')

teacher_app/templates/coursework_adminexam.html
{% extends 'teacher_base.html' %}

{% block title %}作业情况-年级考试{% endblock %}

{% block extra_css %}
<style>
        table tbody tr:hover {
            background-color: #f2f2f2;
        }

        .card-item.card-title:hover {
            background-color: #f2f2f2;
            cursor: pointer;

        }
</style>
{% endblock %}

{% block content %}
<!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-md-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body dashboard-tabs p-0">
                                <div class="tab-content py-0 px-0">
                                    <!--班级完成情况-->
                                    <div class="row">
                                        <div class="col-md-7 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <p class="card-title">班级完成情况</p>
                                                    <div id="cash-deposits-chart-legend"
                                                         class="d-flex justify-content-center pt-3"></div>
                                                    <!-- 为 ECharts 准备一个具备大小（宽高）的 DOM -->
                                                    <div id="cash-deposits-chart"
                                                         style="width: 600px;height:400px;"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--练习考试切换-->
                                        <div class="col-md-5 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <!-- 添加切换按钮 -->
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <button type="button" class="btn btn-secondary exercise-button"
                                                                data-type="exercise">学生练习
                                                        </button>
                                                        <button type="button" class="btn btn-secondary exam-button"
                                                                data-type="exam">班级考试
                                                        </button>
                                                        <button type="button" class="btn btn-secondary"
                                                                data-type="adminexam">年级考试
                                                        </button>
                                                    </div>
                                                    <div class="table-responsive"
                                                         style="max-height: 300px; overflow-y: auto; overflow-x: hidden;">
                                                        <div class="row">
                                                            <table class="table">
                                                                <thead>
                                                                <tr>
                                                                    <th scope="col">名称</th>
                                                                    <th scope="col">开始时间</th>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                {% for question in coursework %}
                                                                    <tr data-id="{{ question.id }}">
                                                                        <td>{{ question.title }}</td>
                                                                        <td>{{ question.starttime }}</td>
                                                                    </tr>
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">班级列表</p>
                            <div class="table-responsive"
                                 style="max-height: 300px; overflow-y: auto; overflow-x: hidden;">
                                <div class="table-responsive">
                                    <div class="card-container">
                                        {% for class in classes %}
                                            <div class="card class-id" data-class-id="{{ class.id }}">
                                                <div class="card-item card-title">{{ class.name }}</div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <!-- partial -->
                            </div>
                            <!-- main-panel ends -->
                        </div>
                        <!-- page-body-wrapper ends -->
                    </div>
                    <!-- container-scroller -->
                </div>
            </div>
        </div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    var myChart = echarts.init(document.getElementById('cash-deposits-chart'));
    var option = {
        tooltip: {},
        legend: {
            data: ['完成情况']
        },
        xAxis: {
            data: ["班级1", "班级2", "班级3", "班级4", "班级5", "班级6"]
        },
        yAxis: {},
        series: [{
            name: '完成情况',
            type: 'bar',
            data: [0.7, 1, 0.2, 0.4, 0.5, 0.1]
        }]
    };
    myChart.setOption(option);
</script>
<script>
    $(function () {
        $('.btn-group .btn-secondary[data-type="adminexam"]').addClass('active')

        $('.btn-group .btn-secondary.exam-button').click(function () {
            window.location.href = "{% url 'teacher_app:coursework_exam' %}"
        });
        $('.btn-group .btn-secondary.exercise-button').click(function () {
            window.location.href = "{% url 'teacher_app:coursework_exercise' %}"
        });

        $('table tbody').on('click', 'tr', function () {
            var id = $(this).data('id');
            var type = $('.btn-group .btn-secondary.active').data('type');
            $.ajax({
                url: "{% url 'teacher_app:coursework_data' %}",
                type: 'POST',
                data: {
                    'id': id,
                    'type': type,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (response) {
                    updateChart(response.data);
                },
                error: function (response) {
                    alert(response.responseJSON.message);
                }
            });
        });
    })

    // 更新柱状图的函数
    function updateChart(data) {
        var myChart = echarts.init(document.getElementById('cash-deposits-chart'));
        var classNames = data.map(function (item) {
            return item.class_name;
        });
        var completionRates = data.map(function (item) {
            return item.completion_rate;
        });
        var option = {
            tooltip: {},
            legend: {
                data: ['完成情况']
            },
            xAxis: {
                data: classNames
            },
            yAxis: {
                type: 'value',
                min: 0,
                max: 1,
                axisLabel: {
                    formatter: function (value) {
                        return (value * 100) + "%";
                    }
                }
            },
            series: [{
                name: '完成情况',
                type: 'bar',
                data: completionRates,
                barWidth: '55'
            }]
        };
        myChart.setOption(option);
    }
</script>
<script>
    $(document).ready(function () {
        $("table tbody tr").click(function () {
            $("table tbody tr").css("background-color", ""); // 添加这行，恢复所有行原本的背景颜色
            $(this).css("background-color", "#f2f2f2"); // 让点击的那一行变为灰色
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('.class-id').on('click', function () {
            var classId = $(this).data('class-id');
            window.location.href = "{% url 'teacher_app:coursework_adminexam_details' '123' %}".replace('123', classId);
        });
    });
</script>
{% endblock %}